TrajectoryPlannerROS:
#DWAPlannerROS:
  #Set the acceleration limits of the robot
  acc_lim_th: 0
  acc_lim_x: 1.7
  acc_lim_y: 1.0

  max_vel_x: 0.6
  min_vel_x: 0.1
  max_vel_y: 0.6
  min_vel_y: -0.6

  max_vel_theta: 0
  min_vel_theta: 0
  min_in_place_vel_theta: 0

  holonomic_robot: true
  meter_scoring: true

  y_vels: [-0.5, 0.5]


  escape_vel: -0.2
  #vtheta_samples: 0
  controller_frequency: 10.0
